language: python
python:
- '3.6'
install: pip install -r requirements.txt -t .
script:
- true
after_success:
- mkdir dist
- find ./ -name '*.pyc' -delete
- zip -r dist/threatstack-to-splunk.zip . -x '.git/*' -x 'dist/*'
- cp deploy/cloudformation.json dist/threatstack-to-splunk.json
- sed -i.bak "s,%%SHA256%%,$(openssl dgst -binary -sha256 dist/threatstack-to-splunk.zip | openssl base64)," dist/threatstack-to-splunk.json
- sed -i.bak "s,%%TRAVIS_BUILD_NUMBER%%,$TRAVIS_BUILD_NUMBER," dist/threatstack-to-splunk.json
- rm dist/*.bak
- ls -al dist
- cat dist/threatstack-to-splunk.json
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: wMHMIt1QXIOfJN2QfG4wb33P4XrYtKiZbyxbzK5b8USKvHJfEd/9Zl7KTKWZBRJJvniwJtXT59D2ZRhCPWLPZb5IIcFnbF2G5wje925tEUaAg93t9mC9sSkk51lsn9zGfMUiEk2MglEH5EoOhViIqETjAGbFn3hDizX9PM4uU31LlxOWMiUjSbsgS0Rwn2rbUjec02NYe1tPtyZ7IBNNZSWjcpjCCu04jKbnGIG5a2/M9NnTc8ZjZr1WAt52ZJt8cQVOxeHhTeuIjqCYvq2WFbn83ugJvkuwKZnYSwnREdr0CCoMSWqoqmSz+inDfGI98OJASxl/kGxYo8JCMvBObLmVhNJkhoHC7FCPMHpQqH9zczOsYhW9J+3Es4o8nenn5t1HN4Mjzoa7olEKEuOic85M0VltMvEndFcdmVWCIRTgldS9c5oD+5qPew+6CgMdf5o1cJFobmR5jwRM/j3ODmeTPMh/QZmixSaxi5c9MXNSu3mgNeJHM3b1OUILeroVIRE2qMqeREaICTYEyM5GDYJlloEByXlh7INRb8idVj6T1YkgMBAY99KPkQ/Hu7+UziA3eJ40Mjyrd5mmL//IYyImsWuDhaq9p0OLPA5VqWW8mbeDzsOATpS8sE9DWqstSOacMLO5Tty9tAEHA+O6KoE6Wzxy81IIfva+lcm/ySE=
  secret_access_key:
    secure: k0uMef6gDWxyWLRfJsvT4jljZRXxOUof9S+nqgxYu9PqKMG8NZoGxpaFn48w+pGaP6tEplmNL2kwp+l09Slu6L0gu/8CvxjYwVwwcSeEQbgG5SV3UcyRaUoP3RT/2C9deIzTByiZTVwiJmAoEes1dtA20XQHFAsTDzr54CSpR7TPSQfJiifP+NTuUedPaYrb+jYh4mKg8Mc8zkRSxMwIWl9MKuNj+fSNcO8Xlu7uF0ltzMxzX3gbkNVUM52Dc+pLiiLMAoGfUsU/4HAAxX5/yXWSR2/OFrPFZVgEFhWi16ZgNn8MQdDGqZh8TPgXaGQN1wNiI62VWV5D7n2kAifR0lFvLAC8XTZe6KsYf6vz6pMxJNSQQ9p7dn9JOmOmPd1cIpCk/SrJ93MQoufXn9YDuh2KQQTL/J1jLOhrVUxDjFzA3xNXQ+LriGTyUTFkAdFb6bUj6H178FvC71X/8+AUW2dSrac4AmEIUOvXC1lLX5QIO7Dss2laNYBZOhFjC1mNF7Tcj+IUkNF2QLIFzeNDCf2m0dBr/z3CJyX4uH/73odKFEmb3ev8Q/LqQOcEKd4r0P1VS3mCnS7r/Q5VAp9/glMm9kWDgNs7G9Bb9y1GAai+DF3RjyLguOkyiX1gg9XOnUKCvoZKKj9tDiqll078u8gcL29QGBWEpdVhfd/Jw8o=
  bucket: ts-demo-lamba-deploys
  local-dir: dist
  acl: public_read
  on:
    repo: threatstack/threatstack-to-splunk
